#!/bin/sh /etc/rc.common

# OpenWrt /etc/init.d/ script to automatically add ipsets across reboots
#
#
# howto:
# - upload this file as /etc/init.d/autoipset
# - # chmod 755 /etc/init.d/autoipset
# - # /etc/init.d/autoipset enable
# - # /etc/init.d/autoipset start

# queue this init script to start (i.e., create IPSet) right before dnsmasq starts (19)
START=18

setipset() {
	ipset -N fbcdn hash:ip
    ipset -N facebook hash:ip
	ipset -N instagram hash:ip
	ipset -N twitter hash:ip
	ipset -N twimg hash:ip
	ipset -N tco hash:ip
	ipset -N zoom hash:ip
	ipset -N cloudfront hash:ip
	ipset -N gmail hash:ip
	ipset -N gdocs hash:ip
	ipset -N gmeet hash:ip
	ipset -N gcalendar hash:ip
	ipset -N gplay hash:ip
	ipset -N hangouts hash:ip
	ipset -N gaccounts hash:ip
	ipset -N gapis hash:ip
	ipset -N githubassets hash:ip
	ipset -N githubapis hash:ip
	ipset -N github hash:ip
	ipset -N githubusercontent hash:ip
	ipset -N wwwhotmail hash:ip
	ipset -N hotmail hash:ip
	ipset -N outlooklive hash:ip
	ipset -N contentstorage hash:ip
	ipset -N outlook1 hash:ip
	ipset -N wso2support hash:ip
}

start() {
	setipset
}