#!/bin/sh /etc/rc.common

# OpenWrt /etc/init.d/ script to automatically add ipsets across reboots
#
#
# howto:
# - upload this file as /etc/init.d/autoipset
# - # chmod 755 /etc/init.d/autoipset
# - # /etc/init.d/autoipset enable
# - # /etc/init.d/autoipset start

# queue this init script to start (i.e., create IPSet) right before dnsmasq starts (19)
### Don't edit this use dnsmasq.parser.py
START=18

setipset() {
	ipset -N facebook hash:ip
	ipset -N instagram hash:ip
	ipset -N fbcdn hash:ip
	ipset -N twitter hash:ip
	ipset -N twimg hash:ip
	ipset -N tco hash:ip
	ipset -N zoom hash:ip
	ipset -N cloudfront hash:ip
	ipset -N gmail hash:ip
	ipset -N gdocs hash:ip
	ipset -N gmeet hash:ip
	ipset -N gcalendar hash:ip
	ipset -N gplay hash:ip
	ipset -N hangouts hash:ip
	ipset -N gaccounts hash:ip
	ipset -N gapis hash:ip
	ipset -N gcontacts hash:ip
	ipset -N fontsgstatic hash:ip
	ipset -N gstatic hash:ip
	ipset -N drivegoogle hash:ip
	ipset -N githubassets hash:ip
	ipset -N githubapis hash:ip
	ipset -N github hash:ip
	ipset -N gitusrcnt hash:ip
	ipset -N wwwhotmail hash:ip
	ipset -N hotmail hash:ip
	ipset -N outlooklive hash:ip
	ipset -N contentstorage hash:ip
	ipset -N outlook1 hash:ip
	ipset -N wso2support hash:ip
	ipset -N apifacebook hash:ip
	ipset -N edgemqttfacebk hash:ip
	ipset -N graphfacebook hash:ip
	ipset -N mqttc10rfacebk hash:ip
	ipset -N portalfbcom hash:ip
	ipset -N starc10rfacebk hash:ip
}

start() {
	setipset
}